#!/usr/bin/env bash
set -euo pipefail

# v0.5: Multi-take recorder with FFT auto-sync for MotionCam Pro
#       Config-driven via devices.yaml (generated by setup_devices.py)
#       Auto-detects audio/video devices, connects wireless, pulls & syncs.
#
# Usage:
#   ./record-mic.sh [session_name]                # record session (multi-take)
#   ./record-mic.sh resync [session]              # re-sync all takes
#   ./record-mic.sh resync [session] 2 +0.5       # resync take 2 with +0.5s adjustment
#   ./record-mic.sh manual [session] 2 12.5       # manual offset for take 2
#   ./record-mic.sh del [session]                 # delete all cache & processed files
#
# Session structure:
#   session_*/
#   ├── .audio_raw/          # mic audio (Samsung) + extracted refs + offsets
#   ├── .video_raw/          # unprocessed videos pulled from Pixel
#   ├── .video_processed/    # individual synced takes (xxx_final.mp4)
#   └── YYYYMMDD_NN.mp4      # all takes concatenated

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
VENV_PYTHON="$SCRIPT_DIR/venv/bin/python3"
DEVICES_YAML="$SCRIPT_DIR/devices.yaml"
LAST_SESSION_FILE="$HOME/.cache/record-mic-last-session"

AUDIO_BITRATE="320k"

# ── Read devices.yaml via Python (no yq dependency) ─────────────────────────
read_device_field() {
    # Usage: read_device_field <role> <field>
    local role="$1" field="$2"
    "$VENV_PYTHON" -c "
import yaml, sys
with open('$DEVICES_YAML') as f:
    cfg = yaml.safe_load(f)
for d in cfg.get('devices', []):
    if d.get('role') == '$role':
        print(d.get('$field', ''))
        sys.exit(0)
print('')
"
}

# ── ADB helpers ──────────────────────────────────────────────────────────────
adb_for() {
    local serial="$1"; shift
    if [[ -n "$serial" ]]; then
        adb -s "$serial" "$@"
    else
        adb "$@"
    fi
}

device_connected() {
    local serial="$1"
    adb devices 2>/dev/null | grep -q "$serial.*device"
}

ensure_device() {
    local name="$1" serial="$2" connection="$3" ip="$4" port="$5"
    local retries=3 delay=2

    if device_connected "$serial"; then
        echo "✓ $name: already connected ($serial)"
        return 0
    fi

    if [[ "$connection" != "wireless" || -z "$ip" ]]; then
        echo "✗ $name: not found on USB ($serial)"
        return 1
    fi

    local addr="$ip:$port"
    for attempt in $(seq 1 "$retries"); do
        echo "  $name: connecting to $addr (attempt $attempt/$retries)..."

        # disconnect stale entry first
        adb disconnect "$addr" &>/dev/null

        local out
        out=$(timeout 5 adb connect "$addr" 2>&1)
        if echo "$out" | grep -q "connected"; then
            # verify it actually shows up as a device
            sleep 0.5
            if device_connected "$addr"; then
                echo "✓ $name: connected wirelessly"
                return 0
            fi
            echo "  $name: adb said connected but device not ready, retrying..."
        else
            echo "  $name: $out"
        fi

        if (( attempt < retries )); then
            sleep "$delay"
        fi
    done

    echo "✗ $name: failed after $retries attempts ($addr)"
    echo "  Hint: make sure the device is awake and on the same Wi-Fi network"
    return 1
}

# ── Timestamp helpers ────────────────────────────────────────────────────────
parse_video_ts() {
    # 260312_182925_VIDEO_... → 20260312182925 (sortable integer)
    local name="$1"
    local ts="${name%%_VIDEO_*}"  # 260312_182925
    echo "20${ts//_/}"           # 20260312182925
}

parse_audio_ts() {
    # recording2026-03-12 10-16-12.wav → 20260312101612
    local name="$1"
    name="${name#recording}"           # 2026-03-12 10-16-12.wav
    name="${name%.wav}"                # 2026-03-12 10-16-12
    name="${name%.m4a}"
    name="${name%.mp3}"
    echo "${name//[-: ]/}"            # 20260312101612
}

find_matching_mic() {
    # Given a video timestamp, find the closest audio that started before it
    local video_ts="$1" session_dir="$2"
    local best="" best_ts=0

    # Check for timestamped mic files first
    local has_named=false
    for mic in "$session_dir"/.audio_raw/mic_*.wav; do
        [[ -f "$mic" ]] || continue
        has_named=true
        local mic_name
        mic_name=$(basename "$mic")        # mic_20260312_101612.wav
        local mic_ts="${mic_name#mic_}"     # 20260312_101612.wav
        mic_ts="${mic_ts%.wav}"             # 20260312_101612
        mic_ts="${mic_ts//_/}"             # 20260312101612
        if (( mic_ts <= video_ts && mic_ts > best_ts )); then
            best="$mic"
            best_ts="$mic_ts"
        fi
    done

    # If no audio started before the video, pick the closest overall
    if [[ -z "$best" && "$has_named" == true ]]; then
        local closest="" closest_diff=999999999999999
        for mic in "$session_dir"/.audio_raw/mic_*.wav; do
            [[ -f "$mic" ]] || continue
            local mic_name
            mic_name=$(basename "$mic")
            local mic_ts="${mic_name#mic_}"
            mic_ts="${mic_ts%.wav}"
            mic_ts="${mic_ts//_/}"
            local diff=$(( video_ts > mic_ts ? video_ts - mic_ts : mic_ts - video_ts ))
            if (( diff < closest_diff )); then
                closest="$mic"
                closest_diff="$diff"
            fi
        done
        best="$closest"
    fi

    # Fallback: legacy mic.wav (single-session backward compat)
    if [[ -z "$best" && -f "$session_dir/.audio_raw/mic.wav" ]]; then
        best="$session_dir/.audio_raw/mic.wav"
    fi

    echo "$best"
}

# ── Sync a single take ──────────────────────────────────────────────────────
sync_take() {
    local SESSION="$1" TAKE_NUM="$2" ADJUST="${3:-0}" MIC="${4:-}"
    local PADNUM
    PADNUM=$(printf "%03d" "$TAKE_NUM")
    local VIDEO_RAW="$SESSION/.video_raw"
    if [[ -z "$MIC" ]]; then
        MIC="$SESSION/.audio_raw/mic.wav"
    fi
    local VIDEO
    VIDEO=$(ls "$VIDEO_RAW/${PADNUM}_"*.mp4 2>/dev/null | head -1)

    if [[ -z "$VIDEO" || ! -f "$VIDEO" ]]; then
        echo "Error: Take $TAKE_NUM not found in $VIDEO_RAW"
        return 1
    fi

    if [[ ! -f "$MIC" ]]; then
        echo "Error: Mic recording not found at $MIC"
        return 1
    fi

    mkdir -p "$SESSION/.video_processed"
    local OUTPUT="$SESSION/.video_processed/${PADNUM}_final.mp4"
    local VDUR
    VDUR=$(ffprobe -v quiet -show_entries format=duration -of csv=p=0 "$VIDEO")

    local HAS_AUDIO
    HAS_AUDIO=$(ffprobe -v quiet -show_streams -select_streams a "$VIDEO" | head -1)

    local OFFSET="0"
    if [[ -n "$HAS_AUDIO" ]]; then
        local REF_WAV="$SESSION/.audio_raw/${PADNUM}_ref.wav"
        ffmpeg -y -i "$VIDEO" -vn -f wav "$REF_WAV" 2>/dev/null
        OFFSET=$("$VENV_PYTHON" "$SCRIPT_DIR/audio_sync.py" "$REF_WAV" "$MIC")
        echo "  Take $TAKE_NUM: auto offset ${OFFSET}s"
    else
        echo "  Take $TAKE_NUM: no reference audio, using offset 0"
    fi

    local FINAL_OFFSET
    FINAL_OFFSET=$("$VENV_PYTHON" -c "print(float('$OFFSET') + float('$ADJUST'))")
    if [[ "$ADJUST" != "0" ]]; then
        echo "  Take $TAKE_NUM: adjustment ${ADJUST}s → final offset ${FINAL_OFFSET}s"
    fi

    echo "$FINAL_OFFSET" > "$SESSION/.audio_raw/${PADNUM}_offset.txt"

    if "$VENV_PYTHON" -c "import sys; sys.exit(0 if float('$FINAL_OFFSET') >= 0 else 1)"; then
        ffmpeg -y -i "$VIDEO" -ss "$FINAL_OFFSET" -i "$MIC" \
            -c:v copy -c:a aac -b:a "$AUDIO_BITRATE" \
            -map 0:v -map 1:a \
            -t "$VDUR" \
            "$OUTPUT" 2>/dev/null
    else
        local PAD
        PAD=$("$VENV_PYTHON" -c "print(abs(float('$FINAL_OFFSET')))")
        ffmpeg -y -i "$VIDEO" -i "$MIC" \
            -filter_complex "[1:a]adelay=${PAD}s|${PAD}s[delayed]" \
            -c:v copy -c:a aac -b:a "$AUDIO_BITRATE" \
            -map 0:v -map "[delayed]" \
            -t "$VDUR" \
            "$OUTPUT" 2>/dev/null
    fi

    echo "  Take $TAKE_NUM: saved $OUTPUT (${VDUR}s)"
}

resolve_session() {
    local NAME="${1:-}"
    if [[ -n "$NAME" && -d "$NAME" ]]; then
        echo "$NAME"
    elif [[ -n "$NAME" && -d "session_$NAME" ]]; then
        echo "session_$NAME"
    elif [[ -z "$NAME" && -f "$LAST_SESSION_FILE" ]]; then
        cat "$LAST_SESSION_FILE"
    else
        echo ""
    fi
}

# ── Main guard: only run side effects when executed directly ─────────────────
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then

# ── Check dependencies ───────────────────────────────────────────────────────
if [[ ! -f "$DEVICES_YAML" ]]; then
    echo "Error: devices.yaml not found. Run: python setup_devices.py"
    exit 1
fi

if [[ ! -f "$VENV_PYTHON" ]]; then
    echo "Error: venv not found at $SCRIPT_DIR/venv"
    echo "Create it: python3 -m venv venv && venv/bin/pip install pyyaml numpy scipy"
    exit 1
fi

# Load video device config
VIDEO_SERIAL=$(read_device_field video serial)
VIDEO_NAME=$(read_device_field video name)
VIDEO_CONNECTION=$(read_device_field video connection)
VIDEO_IP=$(read_device_field video ip)
VIDEO_PORT=$(read_device_field video port)
VIDEO_PULL_DIR=$(read_device_field video pull_dir)

# Load audio device config
AUDIO_SERIAL=$(read_device_field audio serial)
AUDIO_NAME=$(read_device_field audio name)
AUDIO_CONNECTION=$(read_device_field audio connection)
AUDIO_IP=$(read_device_field audio ip)
AUDIO_PORT=$(read_device_field audio port)
AUDIO_PULL_DIR=$(read_device_field audio pull_dir)

if [[ -z "$VIDEO_SERIAL" ]]; then
    echo "Error: No video device configured in devices.yaml"
    echo "Run: python setup_devices.py"
    exit 1
fi

if [[ -z "$AUDIO_SERIAL" ]]; then
    echo "Error: No audio device configured in devices.yaml"
    echo "Run: python setup_devices.py"
    exit 1
fi

# ── DEL ──────────────────────────────────────────────────────────────────────
if [[ "${1:-}" == "del" ]]; then
    if [[ "${2:-}" == "*" ]]; then
        echo "Cleaning all sessions..."
        for SESSION in session_*/; do
            [[ -d "$SESSION" ]] || continue
            echo "  $SESSION"
            rm -rf "$SESSION/.audio_raw" "$SESSION/.video_raw" "$SESSION/.video_processed"
        done
        echo "Done."
        exit 0
    fi

    SESSION=$(resolve_session "${2:-}")
    if [[ -z "$SESSION" || ! -d "$SESSION" ]]; then
        echo "Error: Session not found. Usage: $0 del [session|*]"
        exit 1
    fi

    echo "Cleaning session: $SESSION"
    rm -rf "$SESSION/.audio_raw" "$SESSION/.video_raw" "$SESSION/.video_processed"
    echo "Done."
    ls -1 "$SESSION/"*.mp4 2>/dev/null || echo "  (no finals)"
    exit 0
fi

# ── RESYNC ───────────────────────────────────────────────────────────────────
if [[ "${1:-}" == "resync" ]]; then
    SESSION=$(resolve_session "${2:-}")
    if [[ -z "$SESSION" || ! -d "$SESSION" ]]; then
        echo "Error: Session not found."
        exit 1
    fi

    TAKE="${3:-}"
    ADJUST="${4:-0}"

    # Helper: find mic for a given take number
    resync_find_mic() {
        local sess="$1" take_num="$2"
        local padnum
        padnum=$(printf "%03d" "$take_num")
        local vfile
        vfile=$(ls "$sess/.video_raw/${padnum}_"*.mp4 2>/dev/null | head -1)
        if [[ -n "$vfile" ]]; then
            local vbase
            vbase=$(basename "$vfile")
            local vts
            vts=$(parse_video_ts "${vbase#${padnum}_}")
            find_matching_mic "$vts" "$sess"
        fi
    }

    echo "=== Resyncing: $SESSION ==="
    if [[ -n "$TAKE" ]]; then
        MIC=$(resync_find_mic "$SESSION" "$TAKE")
        if [[ -n "$MIC" ]]; then
            echo "  Take $TAKE: using $(basename "$MIC")"
        fi
        sync_take "$SESSION" "$TAKE" "$ADJUST" "$MIC"
    else
        COUNT=$(ls "$SESSION/.video_raw/"*.mp4 2>/dev/null | wc -l)
        for i in $(seq 1 "$COUNT"); do
            MIC=$(resync_find_mic "$SESSION" "$i")
            if [[ -n "$MIC" ]]; then
                echo "  Take $i: using $(basename "$MIC")"
            fi
            sync_take "$SESSION" "$i" "$ADJUST" "$MIC"
        done
    fi

    COUNT=$(ls "$SESSION/.video_processed/"*_final.mp4 2>/dev/null | wc -l)
    if [[ "$COUNT" -gt 0 ]]; then
        CONCAT_LIST="$SESSION/.video_raw/concat.txt"
        > "$CONCAT_LIST"
        for f in "$SESSION/.video_processed/"*_final.mp4; do
            echo "file '$(realpath "$f")'" >> "$CONCAT_LIST"
        done
        ffmpeg -y -f concat -safe 0 -i "$CONCAT_LIST" -c copy "$SESSION/final.mp4" 2>/dev/null
        echo "Combined: $SESSION/final.mp4"
    fi

    echo "Done."
    exit 0
fi

# ── MANUAL ───────────────────────────────────────────────────────────────────
if [[ "${1:-}" == "manual" ]]; then
    SESSION=$(resolve_session "${2:-}")
    TAKE="${3:?Usage: $0 manual [session] <take_num> <offset>}"
    MANUAL_OFFSET="${4:?Usage: $0 manual [session] <take_num> <offset>}"

    if [[ -z "$SESSION" || ! -d "$SESSION" ]]; then
        echo "Error: Session not found."
        exit 1
    fi

    PADNUM=$(printf "%03d" "$TAKE")
    VIDEO=$(ls "$SESSION/.video_raw/${PADNUM}_"*.mp4 2>/dev/null | head -1)
    VIDEO_BASE=$(basename "$VIDEO")
    VIDEO_TS=$(parse_video_ts "${VIDEO_BASE#${PADNUM}_}")
    MIC=$(find_matching_mic "$VIDEO_TS" "$SESSION")
    if [[ -z "$MIC" ]]; then
        MIC="$SESSION/.audio_raw/mic.wav"
    fi
    echo "Using audio: $(basename "$MIC")"
    mkdir -p "$SESSION/.video_processed"
    OUTPUT="$SESSION/.video_processed/${PADNUM}_final.mp4"
    VDUR=$(ffprobe -v quiet -show_entries format=duration -of csv=p=0 "$VIDEO")

    echo "=== Manual sync: take $TAKE, offset ${MANUAL_OFFSET}s ==="
    echo "$MANUAL_OFFSET" > "$SESSION/.audio_raw/${PADNUM}_offset.txt"

    if "$VENV_PYTHON" -c "import sys; sys.exit(0 if float('$MANUAL_OFFSET') >= 0 else 1)"; then
        ffmpeg -y -i "$VIDEO" -ss "$MANUAL_OFFSET" -i "$MIC" \
            -c:v copy -c:a aac -b:a "$AUDIO_BITRATE" \
            -map 0:v -map 1:a \
            -t "$VDUR" \
            "$OUTPUT" 2>/dev/null
    else
        PAD=$("$VENV_PYTHON" -c "print(abs(float('$MANUAL_OFFSET')))")
        ffmpeg -y -i "$VIDEO" -i "$MIC" \
            -filter_complex "[1:a]adelay=${PAD}s|${PAD}s[delayed]" \
            -c:v copy -c:a aac -b:a "$AUDIO_BITRATE" \
            -map 0:v -map "[delayed]" \
            -t "$VDUR" \
            "$OUTPUT" 2>/dev/null
    fi

    echo "Saved: $OUTPUT"
    exit 0
fi

# ── RECORD MODE ──────────────────────────────────────────────────────────────
SESSION_NAME="${1:-session_$(date +%Y%m%d_%H%M%S)}"
SESSION_DIR="$SESSION_NAME"

mkdir -p "$SESSION_DIR/.audio_raw" "$SESSION_DIR/.video_raw" "$SESSION_DIR/.video_processed"
mkdir -p "$(dirname "$LAST_SESSION_FILE")"
echo "$SESSION_DIR" > "$LAST_SESSION_FILE"

echo ""
echo "=== 🎬 Video: $VIDEO_NAME ($VIDEO_CONNECTION) ==="
echo "=== 🎙  Audio: $AUDIO_NAME ($AUDIO_CONNECTION) ==="
echo ""

# ── Connect devices ──────────────────────────────────────────────────────────
CONNECT_OK=true
ensure_device "$VIDEO_NAME" "$VIDEO_SERIAL" "$VIDEO_CONNECTION" "$VIDEO_IP" "$VIDEO_PORT" || CONNECT_OK=false
ensure_device "$AUDIO_NAME" "$AUDIO_SERIAL" "$AUDIO_CONNECTION" "$AUDIO_IP" "$AUDIO_PORT" || CONNECT_OK=false
if [[ "$CONNECT_OK" != true ]]; then
    echo ""
    echo "Aborting: not all devices are reachable."
    exit 1
fi

echo ""
echo "=== Session: $SESSION_DIR ==="
echo ""
echo "Make sure you've recorded video on $VIDEO_NAME + audio on $AUDIO_NAME."
echo "Press ENTER to pull and sync."
read -r

# ── Manifests (track what's already been processed) ──────────────────────────
VIDEO_MANIFEST="$HOME/.cache/record-mic-video-processed.txt"
AUDIO_MANIFEST="$HOME/.cache/record-mic-audio-processed.txt"
touch "$VIDEO_MANIFEST" "$AUDIO_MANIFEST"

# ── Pull videos ──────────────────────────────────────────────────────────────
echo ""
echo "=== Scanning $VIDEO_NAME for videos ==="

ALL_VIDEOS=$(adb_for "$VIDEO_SERIAL" shell "ls -1t '$VIDEO_PULL_DIR'/*.mp4 2>/dev/null || true" | tr -d '\r')

NEW_VIDEOS=""
while IFS= read -r VIDEO_REMOTE; do
    [[ -z "$VIDEO_REMOTE" ]] && continue
    BASENAME=$(basename "$VIDEO_REMOTE")
    if ! grep -qxF "$BASENAME" "$VIDEO_MANIFEST"; then
        NEW_VIDEOS="${NEW_VIDEOS}${VIDEO_REMOTE}"$'\n'
    fi
done <<< "$ALL_VIDEOS"
NEW_VIDEOS=$(echo "$NEW_VIDEOS" | sed '/^$/d' | sort)

TAKE_NUM=0
if [[ -z "$NEW_VIDEOS" ]]; then
    echo "No unprocessed videos found on $VIDEO_NAME."
    echo "To reprocess, edit: $VIDEO_MANIFEST"
else
    VIDEO_COUNT=$(echo "$NEW_VIDEOS" | wc -l)
    echo "Found $VIDEO_COUNT unprocessed video(s):"
    echo "$NEW_VIDEOS" | while read -r f; do echo "  $(basename "$f")"; done
    echo ""

    while IFS= read -r VIDEO_REMOTE; do
        TAKE_NUM=$((TAKE_NUM + 1))
        PADNUM=$(printf "%03d" "$TAKE_NUM")
        BASENAME=$(basename "$VIDEO_REMOTE")
        LOCAL_NAME="${PADNUM}_${BASENAME}"

        printf "  Pulling take $TAKE_NUM: $BASENAME  "
        if ! adb_for "$VIDEO_SERIAL" pull "$VIDEO_REMOTE" "$SESSION_DIR/.video_raw/$LOCAL_NAME" 2>&1 | tr '\n' '\r'; then
            echo
            echo "  WARNING: failed to pull $BASENAME, skipping"
            TAKE_NUM=$((TAKE_NUM - 1))
            continue
        fi
        echo

        echo "$BASENAME" >> "$VIDEO_MANIFEST"
    done <<< "$NEW_VIDEOS"
fi

# ── Pull audio ───────────────────────────────────────────────────────────────
echo ""
echo "=== Scanning $AUDIO_NAME for audio recordings ==="

ALL_AUDIO=$(adb_for "$AUDIO_SERIAL" shell "ls -1t '$AUDIO_PULL_DIR'/*.wav '$AUDIO_PULL_DIR'/*.m4a '$AUDIO_PULL_DIR'/*.mp3 2>/dev/null || true" | tr -d '\r')

NEW_AUDIO=""
while IFS= read -r REC_REMOTE; do
    [[ -z "$REC_REMOTE" ]] && continue
    REC_BASE=$(basename "$REC_REMOTE")
    if ! grep -qxF "$REC_BASE" "$AUDIO_MANIFEST"; then
        NEW_AUDIO="${NEW_AUDIO}${REC_REMOTE}"$'\n'
    fi
done <<< "$ALL_AUDIO"
NEW_AUDIO=$(echo "$NEW_AUDIO" | sed '/^$/d')

if [[ -z "$NEW_AUDIO" ]]; then
    echo "No unprocessed audio recordings found on $AUDIO_NAME."
    echo "To reprocess, edit: $AUDIO_MANIFEST"
fi

if [[ -z "$NEW_VIDEOS" && -z "$NEW_AUDIO" ]]; then
    echo ""
    echo "Nothing to do — no unprocessed videos or audio."
    exit 0
fi

if [[ -n "$NEW_AUDIO" ]]; then
    AUDIO_COUNT=$(echo "$NEW_AUDIO" | wc -l)
    echo "Found $AUDIO_COUNT unprocessed recording(s):"
    echo "$NEW_AUDIO" | while read -r f; do echo "  $(basename "$f")"; done
    echo ""

    while IFS= read -r REC_REMOTE; do
        [[ -z "$REC_REMOTE" ]] && continue
        REC_BASE=$(basename "$REC_REMOTE")
        AUDIO_TS=$(parse_audio_ts "$REC_BASE")
        AUDIO_LOCAL="$SESSION_DIR/.audio_raw/phone_raw_${REC_BASE}"
        MIC_NAMED="$SESSION_DIR/.audio_raw/mic_${AUDIO_TS:0:8}_${AUDIO_TS:8}.wav"

        printf "  Pulling audio: $REC_BASE  "
        if ! adb_for "$AUDIO_SERIAL" pull "$REC_REMOTE" "$AUDIO_LOCAL" 2>&1 | tr '\n' '\r'; then
            echo
            echo "  WARNING: failed to pull $REC_BASE, skipping"
            continue
        fi
        echo

        echo "  Converting → $(basename "$MIC_NAMED")"
        ffmpeg -y -i "$AUDIO_LOCAL" -ar 48000 -ac 1 "$MIC_NAMED" 2>/dev/null

        echo "$REC_BASE" >> "$AUDIO_MANIFEST"
    done <<< "$NEW_AUDIO"
fi

echo "Audio ready: $(ls -1 "$SESSION_DIR/.audio_raw/mic_"*.wav 2>/dev/null | wc -l) recording(s)"

# ── Sync all takes (match each video to its correct audio) ───────────────────
echo ""
echo "=== Syncing $TAKE_NUM take(s) ==="
echo ""

# Track which mic file each take uses (for grouping during concatenation)
declare -A TAKE_MIC_MAP

for i in $(seq 1 "$TAKE_NUM"); do
    PADNUM=$(printf "%03d" "$i")
    VIDEO_FILE=$(ls "$SESSION_DIR/.video_raw/${PADNUM}_"*.mp4 2>/dev/null | head -1)
    if [[ -z "$VIDEO_FILE" ]]; then
        echo "  Take $i: ERROR — video file not found"
        continue
    fi
    VIDEO_BASE=$(basename "$VIDEO_FILE")
    VIDEO_TS=$(parse_video_ts "${VIDEO_BASE#${PADNUM}_}")
    MIC=$(find_matching_mic "$VIDEO_TS" "$SESSION_DIR")
    if [[ -z "$MIC" ]]; then
        echo "  Take $i: ERROR — no matching audio recording found"
        continue
    fi
    echo "  Take $i: using $(basename "$MIC")"
    TAKE_MIC_MAP[$i]="$MIC"
    sync_take "$SESSION_DIR" "$i" "0" "$MIC"
done

# ── Concatenate (grouped by audio session) ───────────────────────────────────
echo ""

# Collect unique mic files used, preserving order
declare -a MIC_ORDER=()
declare -A MIC_SEEN=()
for i in $(seq 1 "$TAKE_NUM"); do
    mic="${TAKE_MIC_MAP[$i]:-}"
    [[ -z "$mic" ]] && continue
    if [[ -z "${MIC_SEEN[$mic]:-}" ]]; then
        MIC_ORDER+=("$mic")
        MIC_SEEN[$mic]=1
    fi
done

if [[ ${#MIC_ORDER[@]} -le 1 ]]; then
    # Single audio session — concatenate all takes into one file
    TODAY=$(date +%Y%m%d)
    EXISTING=$(ls -1 "$SESSION_DIR/" 2>/dev/null | grep -cE "^${TODAY}_[0-9]+\.mp4$" || true)
    EXISTING=${EXISTING:-0}
    FINAL_NUM=$((EXISTING + 1))
    FINAL_OUTPUT="$SESSION_DIR/${TODAY}_$(printf "%02d" "$FINAL_NUM").mp4"
    CONCAT_LIST="$SESSION_DIR/.video_raw/concat.txt"
    > "$CONCAT_LIST"
    for i in $(seq 1 "$TAKE_NUM"); do
        PADNUM=$(printf "%03d" "$i")
        TAKE_FILE="$(realpath "$SESSION_DIR/.video_processed/${PADNUM}_final.mp4" 2>/dev/null)"
        if [[ -f "$TAKE_FILE" ]]; then
            echo "file '$TAKE_FILE'" >> "$CONCAT_LIST"
        fi
    done

    echo "Concatenating all takes..."
    ffmpeg -y -f concat -safe 0 -i "$CONCAT_LIST" -c copy "$FINAL_OUTPUT" 2>/dev/null

    echo ""
    echo "=== Session complete: $SESSION_DIR ==="
    echo "$TAKE_NUM take(s) synced."
    echo ""
    echo "Individual takes:"
    ls -1 "$SESSION_DIR/.video_processed/"*_final.mp4 2>/dev/null
    echo ""
    echo "Combined: $FINAL_OUTPUT"
else
    # Multiple audio sessions — concatenate takes per session
    echo "Multiple audio sessions detected (${#MIC_ORDER[@]}). Concatenating per session."
    echo ""

    declare -a FINAL_OUTPUTS=()
    for mic in "${MIC_ORDER[@]}"; do
        MIC_BASE=$(basename "$mic" .wav)      # mic_20260312_101612
        MIC_DATE="${MIC_BASE#mic_}"            # 20260312_101612 or fallback
        CONCAT_LIST="$SESSION_DIR/.video_raw/concat_${MIC_DATE}.txt"
        > "$CONCAT_LIST"
        CONCAT_COUNT=0
        for i in $(seq 1 "$TAKE_NUM"); do
            if [[ "${TAKE_MIC_MAP[$i]:-}" == "$mic" ]]; then
                PADNUM=$(printf "%03d" "$i")
                TAKE_FILE="$(realpath "$SESSION_DIR/.video_processed/${PADNUM}_final.mp4" 2>/dev/null)"
                if [[ -f "$TAKE_FILE" ]]; then
                    echo "file '$TAKE_FILE'" >> "$CONCAT_LIST"
                    CONCAT_COUNT=$((CONCAT_COUNT + 1))
                fi
            fi
        done

        if [[ "$CONCAT_COUNT" -gt 0 ]]; then
            FINAL_OUTPUT="$SESSION_DIR/${MIC_DATE}.mp4"
            echo "  Session $MIC_DATE: $CONCAT_COUNT take(s) → $FINAL_OUTPUT"
            ffmpeg -y -f concat -safe 0 -i "$CONCAT_LIST" -c copy "$FINAL_OUTPUT" 2>/dev/null
            FINAL_OUTPUTS+=("$FINAL_OUTPUT")
        fi
    done

    echo ""
    echo "=== Session complete: $SESSION_DIR ==="
    echo "$TAKE_NUM take(s) synced across ${#MIC_ORDER[@]} audio session(s)."
    echo ""
    echo "Individual takes:"
    ls -1 "$SESSION_DIR/.video_processed/"*_final.mp4 2>/dev/null
    echo ""
    echo "Combined outputs:"
    for f in "${FINAL_OUTPUTS[@]}"; do echo "  $f"; done
fi

fi # end main guard
