#!/usr/bin/env bash
set -euo pipefail

# v0.5: Multi-take recorder with FFT auto-sync for MotionCam Pro
#       Config-driven via devices.yaml (generated by setup_devices.py)
#       Auto-detects audio/video devices, connects wireless, pulls & syncs.
#
# Usage:
#   ./record-mic.sh [session_name]                # record session (multi-take)
#   ./record-mic.sh resync [session]              # re-sync all takes
#   ./record-mic.sh resync [session] 2 +0.5       # resync take 2 with +0.5s adjustment
#   ./record-mic.sh manual [session] 2 12.5       # manual offset for take 2
#   ./record-mic.sh del [session]                 # delete all cache & processed files
#
# Session structure:
#   session_*/
#   ├── .audio_raw/          # mic audio (Samsung) + extracted refs + offsets
#   ├── .video_raw/          # unprocessed videos pulled from Pixel
#   ├── .video_processed/    # individual synced takes (xxx_final.mp4)
#   └── YYYYMMDD_NN.mp4      # all takes concatenated

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
VENV_PYTHON="$SCRIPT_DIR/venv/bin/python3"
DEVICES_YAML="$SCRIPT_DIR/devices.yaml"
LAST_SESSION_FILE="$HOME/.cache/record-mic-last-session"

AUDIO_BITRATE="320k"

# ── Check dependencies ───────────────────────────────────────────────────────
if [[ ! -f "$DEVICES_YAML" ]]; then
    echo "Error: devices.yaml not found. Run: python setup_devices.py"
    exit 1
fi

if [[ ! -f "$VENV_PYTHON" ]]; then
    echo "Error: venv not found at $SCRIPT_DIR/venv"
    echo "Create it: python3 -m venv venv && venv/bin/pip install pyyaml numpy scipy"
    exit 1
fi

# ── Read devices.yaml via Python (no yq dependency) ─────────────────────────
read_device_field() {
    # Usage: read_device_field <role> <field>
    local role="$1" field="$2"
    "$VENV_PYTHON" -c "
import yaml, sys
with open('$DEVICES_YAML') as f:
    cfg = yaml.safe_load(f)
for d in cfg.get('devices', []):
    if d.get('role') == '$role':
        print(d.get('$field', ''))
        sys.exit(0)
print('')
"
}

# Load video device config
VIDEO_SERIAL=$(read_device_field video serial)
VIDEO_NAME=$(read_device_field video name)
VIDEO_CONNECTION=$(read_device_field video connection)
VIDEO_IP=$(read_device_field video ip)
VIDEO_PORT=$(read_device_field video port)
VIDEO_PULL_DIR=$(read_device_field video pull_dir)

# Load audio device config
AUDIO_SERIAL=$(read_device_field audio serial)
AUDIO_NAME=$(read_device_field audio name)
AUDIO_CONNECTION=$(read_device_field audio connection)
AUDIO_IP=$(read_device_field audio ip)
AUDIO_PORT=$(read_device_field audio port)
AUDIO_PULL_DIR=$(read_device_field audio pull_dir)

if [[ -z "$VIDEO_SERIAL" ]]; then
    echo "Error: No video device configured in devices.yaml"
    echo "Run: python setup_devices.py"
    exit 1
fi

if [[ -z "$AUDIO_SERIAL" ]]; then
    echo "Error: No audio device configured in devices.yaml"
    echo "Run: python setup_devices.py"
    exit 1
fi

# ── ADB helpers ──────────────────────────────────────────────────────────────
adb_for() {
    local serial="$1"; shift
    if [[ -n "$serial" ]]; then
        adb -s "$serial" "$@"
    else
        adb "$@"
    fi
}

device_connected() {
    local serial="$1"
    adb devices 2>/dev/null | grep -q "$serial.*device"
}

ensure_device() {
    local name="$1" serial="$2" connection="$3" ip="$4" port="$5"

    if device_connected "$serial"; then
        echo "✓ $name: connected ($serial)"
        return 0
    fi

    if [[ "$connection" == "wireless" && -n "$ip" ]]; then
        echo "  $name: connecting to $ip:$port..."
        if timeout 5 adb connect "$ip:$port" 2>&1 | grep -q "connected"; then
            echo "✓ $name: connected wirelessly"
            return 0
        fi
    fi

    echo "✗ $name: cannot connect ($serial)"
    exit 1
}

# ── Sync a single take ──────────────────────────────────────────────────────
sync_take() {
    local SESSION="$1" TAKE_NUM="$2" ADJUST="${3:-0}"
    local PADNUM
    PADNUM=$(printf "%03d" "$TAKE_NUM")
    local VIDEO_RAW="$SESSION/.video_raw"
    local MIC="$SESSION/.audio_raw/mic.wav"
    local VIDEO
    VIDEO=$(ls "$VIDEO_RAW/${PADNUM}_"*.mp4 2>/dev/null | head -1)

    if [[ -z "$VIDEO" || ! -f "$VIDEO" ]]; then
        echo "Error: Take $TAKE_NUM not found in $VIDEO_RAW"
        return 1
    fi

    if [[ ! -f "$MIC" ]]; then
        echo "Error: Mic recording not found at $MIC"
        return 1
    fi

    mkdir -p "$SESSION/.video_processed"
    local OUTPUT="$SESSION/.video_processed/${PADNUM}_final.mp4"
    local VDUR
    VDUR=$(ffprobe -v quiet -show_entries format=duration -of csv=p=0 "$VIDEO")

    local HAS_AUDIO
    HAS_AUDIO=$(ffprobe -v quiet -show_streams -select_streams a "$VIDEO" | head -1)

    local OFFSET="0"
    if [[ -n "$HAS_AUDIO" ]]; then
        local REF_WAV="$SESSION/.audio_raw/${PADNUM}_ref.wav"
        ffmpeg -y -i "$VIDEO" -vn -f wav "$REF_WAV" 2>/dev/null
        OFFSET=$("$VENV_PYTHON" "$SCRIPT_DIR/audio_sync.py" "$REF_WAV" "$MIC")
        echo "  Take $TAKE_NUM: auto offset ${OFFSET}s"
    else
        echo "  Take $TAKE_NUM: no reference audio, using offset 0"
    fi

    local FINAL_OFFSET
    FINAL_OFFSET=$("$VENV_PYTHON" -c "print(float('$OFFSET') + float('$ADJUST'))")
    if [[ "$ADJUST" != "0" ]]; then
        echo "  Take $TAKE_NUM: adjustment ${ADJUST}s → final offset ${FINAL_OFFSET}s"
    fi

    echo "$FINAL_OFFSET" > "$SESSION/.audio_raw/${PADNUM}_offset.txt"

    if "$VENV_PYTHON" -c "import sys; sys.exit(0 if float('$FINAL_OFFSET') >= 0 else 1)"; then
        ffmpeg -y -i "$VIDEO" -ss "$FINAL_OFFSET" -i "$MIC" \
            -c:v copy -c:a aac -b:a "$AUDIO_BITRATE" \
            -map 0:v -map 1:a \
            -t "$VDUR" \
            "$OUTPUT" 2>/dev/null
    else
        local PAD
        PAD=$("$VENV_PYTHON" -c "print(abs(float('$FINAL_OFFSET')))")
        ffmpeg -y -i "$VIDEO" -i "$MIC" \
            -filter_complex "[1:a]adelay=${PAD}s|${PAD}s[delayed]" \
            -c:v copy -c:a aac -b:a "$AUDIO_BITRATE" \
            -map 0:v -map "[delayed]" \
            -t "$VDUR" \
            "$OUTPUT" 2>/dev/null
    fi

    echo "  Take $TAKE_NUM: saved $OUTPUT (${VDUR}s)"
}

resolve_session() {
    local NAME="${1:-}"
    if [[ -n "$NAME" && -d "$NAME" ]]; then
        echo "$NAME"
    elif [[ -n "$NAME" && -d "session_$NAME" ]]; then
        echo "session_$NAME"
    elif [[ -z "$NAME" && -f "$LAST_SESSION_FILE" ]]; then
        cat "$LAST_SESSION_FILE"
    else
        echo ""
    fi
}

# ── DEL ──────────────────────────────────────────────────────────────────────
if [[ "${1:-}" == "del" ]]; then
    if [[ "${2:-}" == "*" ]]; then
        echo "Cleaning all sessions..."
        for SESSION in session_*/; do
            [[ -d "$SESSION" ]] || continue
            echo "  $SESSION"
            rm -rf "$SESSION/.audio_raw" "$SESSION/.video_raw" "$SESSION/.video_processed"
        done
        echo "Done."
        exit 0
    fi

    SESSION=$(resolve_session "${2:-}")
    if [[ -z "$SESSION" || ! -d "$SESSION" ]]; then
        echo "Error: Session not found. Usage: $0 del [session|*]"
        exit 1
    fi

    echo "Cleaning session: $SESSION"
    rm -rf "$SESSION/.audio_raw" "$SESSION/.video_raw" "$SESSION/.video_processed"
    echo "Done."
    ls -1 "$SESSION/"*.mp4 2>/dev/null || echo "  (no finals)"
    exit 0
fi

# ── RESYNC ───────────────────────────────────────────────────────────────────
if [[ "${1:-}" == "resync" ]]; then
    SESSION=$(resolve_session "${2:-}")
    if [[ -z "$SESSION" || ! -d "$SESSION" ]]; then
        echo "Error: Session not found."
        exit 1
    fi

    TAKE="${3:-}"
    ADJUST="${4:-0}"

    echo "=== Resyncing: $SESSION ==="
    if [[ -n "$TAKE" ]]; then
        sync_take "$SESSION" "$TAKE" "$ADJUST"
    else
        COUNT=$(ls "$SESSION/.video_raw/"*.mp4 2>/dev/null | wc -l)
        for i in $(seq 1 "$COUNT"); do
            sync_take "$SESSION" "$i" "$ADJUST"
        done
    fi

    COUNT=$(ls "$SESSION/.video_processed/"*_final.mp4 2>/dev/null | wc -l)
    if [[ "$COUNT" -gt 0 ]]; then
        CONCAT_LIST="$SESSION/.video_raw/concat.txt"
        > "$CONCAT_LIST"
        for f in "$SESSION/.video_processed/"*_final.mp4; do
            echo "file '$(realpath "$f")'" >> "$CONCAT_LIST"
        done
        ffmpeg -y -f concat -safe 0 -i "$CONCAT_LIST" -c copy "$SESSION/final.mp4" 2>/dev/null
        echo "Combined: $SESSION/final.mp4"
    fi

    echo "Done."
    exit 0
fi

# ── MANUAL ───────────────────────────────────────────────────────────────────
if [[ "${1:-}" == "manual" ]]; then
    SESSION=$(resolve_session "${2:-}")
    TAKE="${3:?Usage: $0 manual [session] <take_num> <offset>}"
    MANUAL_OFFSET="${4:?Usage: $0 manual [session] <take_num> <offset>}"

    if [[ -z "$SESSION" || ! -d "$SESSION" ]]; then
        echo "Error: Session not found."
        exit 1
    fi

    PADNUM=$(printf "%03d" "$TAKE")
    VIDEO=$(ls "$SESSION/.video_raw/${PADNUM}_"*.mp4 2>/dev/null | head -1)
    MIC="$SESSION/.audio_raw/mic.wav"
    mkdir -p "$SESSION/.video_processed"
    OUTPUT="$SESSION/.video_processed/${PADNUM}_final.mp4"
    VDUR=$(ffprobe -v quiet -show_entries format=duration -of csv=p=0 "$VIDEO")

    echo "=== Manual sync: take $TAKE, offset ${MANUAL_OFFSET}s ==="
    echo "$MANUAL_OFFSET" > "$SESSION/.audio_raw/${PADNUM}_offset.txt"

    if "$VENV_PYTHON" -c "import sys; sys.exit(0 if float('$MANUAL_OFFSET') >= 0 else 1)"; then
        ffmpeg -y -i "$VIDEO" -ss "$MANUAL_OFFSET" -i "$MIC" \
            -c:v copy -c:a aac -b:a "$AUDIO_BITRATE" \
            -map 0:v -map 1:a \
            -t "$VDUR" \
            "$OUTPUT" 2>/dev/null
    else
        PAD=$("$VENV_PYTHON" -c "print(abs(float('$MANUAL_OFFSET')))")
        ffmpeg -y -i "$VIDEO" -i "$MIC" \
            -filter_complex "[1:a]adelay=${PAD}s|${PAD}s[delayed]" \
            -c:v copy -c:a aac -b:a "$AUDIO_BITRATE" \
            -map 0:v -map "[delayed]" \
            -t "$VDUR" \
            "$OUTPUT" 2>/dev/null
    fi

    echo "Saved: $OUTPUT"
    exit 0
fi

# ── RECORD MODE ──────────────────────────────────────────────────────────────
SESSION_NAME="${1:-session_$(date +%Y%m%d_%H%M%S)}"
SESSION_DIR="$SESSION_NAME"

mkdir -p "$SESSION_DIR/.audio_raw" "$SESSION_DIR/.video_raw" "$SESSION_DIR/.video_processed"
mkdir -p "$(dirname "$LAST_SESSION_FILE")"
echo "$SESSION_DIR" > "$LAST_SESSION_FILE"

MIC_WAV="$SESSION_DIR/.audio_raw/mic.wav"

echo ""
echo "=== 🎬 Video: $VIDEO_NAME ($VIDEO_CONNECTION) ==="
echo "=== 🎙  Audio: $AUDIO_NAME ($AUDIO_CONNECTION) ==="
echo ""

# ── Connect devices ──────────────────────────────────────────────────────────
ensure_device "$VIDEO_NAME" "$VIDEO_SERIAL" "$VIDEO_CONNECTION" "$VIDEO_IP" "$VIDEO_PORT"
ensure_device "$AUDIO_NAME" "$AUDIO_SERIAL" "$AUDIO_CONNECTION" "$AUDIO_IP" "$AUDIO_PORT"

echo ""
echo "=== Session: $SESSION_DIR ==="
echo ""
echo "Make sure you've recorded video on $VIDEO_NAME + audio on $AUDIO_NAME."
echo "Press ENTER to pull and sync."
read -r

# ── Manifests (track what's already been processed) ──────────────────────────
VIDEO_MANIFEST="$HOME/.cache/record-mic-video-processed.txt"
AUDIO_MANIFEST="$HOME/.cache/record-mic-audio-processed.txt"
touch "$VIDEO_MANIFEST" "$AUDIO_MANIFEST"

# ── Pull videos ──────────────────────────────────────────────────────────────
echo ""
echo "=== Scanning $VIDEO_NAME for videos ==="

ALL_VIDEOS=$(adb_for "$VIDEO_SERIAL" shell "ls -1t '$VIDEO_PULL_DIR'/*.mp4 2>/dev/null || true" | tr -d '\r')

NEW_VIDEOS=""
while IFS= read -r VIDEO_REMOTE; do
    [[ -z "$VIDEO_REMOTE" ]] && continue
    BASENAME=$(basename "$VIDEO_REMOTE")
    if ! grep -qxF "$BASENAME" "$VIDEO_MANIFEST"; then
        NEW_VIDEOS="${NEW_VIDEOS}${VIDEO_REMOTE}"$'\n'
    fi
done <<< "$ALL_VIDEOS"
NEW_VIDEOS=$(echo "$NEW_VIDEOS" | sed '/^$/d' | sort)

if [[ -z "$NEW_VIDEOS" ]]; then
    echo "No unprocessed videos found on $VIDEO_NAME."
    echo "To reprocess, edit: $VIDEO_MANIFEST"
    exit 1
fi

VIDEO_COUNT=$(echo "$NEW_VIDEOS" | wc -l)
echo "Found $VIDEO_COUNT unprocessed video(s):"
echo "$NEW_VIDEOS" | while read -r f; do echo "  $(basename "$f")"; done
echo ""

TAKE_NUM=0
while IFS= read -r VIDEO_REMOTE; do
    TAKE_NUM=$((TAKE_NUM + 1))
    PADNUM=$(printf "%03d" "$TAKE_NUM")
    BASENAME=$(basename "$VIDEO_REMOTE")
    LOCAL_NAME="${PADNUM}_${BASENAME}"

    echo "Pulling take $TAKE_NUM: $BASENAME"
    adb_for "$VIDEO_SERIAL" pull "$VIDEO_REMOTE" "$SESSION_DIR/.video_raw/$LOCAL_NAME" 2>&1

    echo "$BASENAME" >> "$VIDEO_MANIFEST"
done <<< "$NEW_VIDEOS"

# ── Pull audio ───────────────────────────────────────────────────────────────
echo ""
echo "=== Scanning $AUDIO_NAME for audio recordings ==="

ALL_AUDIO=$(adb_for "$AUDIO_SERIAL" shell "ls -1t '$AUDIO_PULL_DIR'/*.wav '$AUDIO_PULL_DIR'/*.m4a '$AUDIO_PULL_DIR'/*.mp3 2>/dev/null || true" | tr -d '\r')

NEW_AUDIO=""
while IFS= read -r REC_REMOTE; do
    [[ -z "$REC_REMOTE" ]] && continue
    REC_BASE=$(basename "$REC_REMOTE")
    if ! grep -qxF "$REC_BASE" "$AUDIO_MANIFEST"; then
        NEW_AUDIO="${NEW_AUDIO}${REC_REMOTE}"$'\n'
    fi
done <<< "$ALL_AUDIO"
NEW_AUDIO=$(echo "$NEW_AUDIO" | sed '/^$/d')

if [[ -z "$NEW_AUDIO" ]]; then
    echo "No unprocessed audio recordings found on $AUDIO_NAME."
    echo "To reprocess, edit: $AUDIO_MANIFEST"
    exit 1
fi

AUDIO_LATEST=$(echo "$NEW_AUDIO" | head -1)
AUDIO_BASENAME=$(basename "$AUDIO_LATEST")
AUDIO_LOCAL="$SESSION_DIR/.audio_raw/phone_raw_${AUDIO_BASENAME}"

AUDIO_COUNT=$(echo "$NEW_AUDIO" | wc -l)
echo "Found $AUDIO_COUNT unprocessed recording(s). Using latest: $AUDIO_BASENAME"

echo "Pulling audio: $AUDIO_BASENAME"
adb_for "$AUDIO_SERIAL" pull "$AUDIO_LATEST" "$AUDIO_LOCAL" 2>&1

echo "Converting to mic.wav..."
ffmpeg -y -i "$AUDIO_LOCAL" -ar 48000 -ac 1 "$MIC_WAV" 2>/dev/null
echo "Audio ready: $MIC_WAV"

echo "$AUDIO_BASENAME" >> "$AUDIO_MANIFEST"

# ── Sync all takes ───────────────────────────────────────────────────────────
echo ""
echo "=== Syncing $TAKE_NUM take(s) ==="
echo ""

for i in $(seq 1 "$TAKE_NUM"); do
    sync_take "$SESSION_DIR" "$i"
done

# ── Concatenate ──────────────────────────────────────────────────────────────
TODAY=$(date +%Y%m%d)
EXISTING=$(ls -1 "$SESSION_DIR/" 2>/dev/null | grep -cE "^${TODAY}_[0-9]+\.mp4$" || true)
EXISTING=${EXISTING:-0}
FINAL_NUM=$((EXISTING + 1))
FINAL_OUTPUT="$SESSION_DIR/${TODAY}_$(printf "%02d" "$FINAL_NUM").mp4"
CONCAT_LIST="$SESSION_DIR/.video_raw/concat.txt"
> "$CONCAT_LIST"
for i in $(seq 1 "$TAKE_NUM"); do
    PADNUM=$(printf "%03d" "$i")
    TAKE_FILE="$(realpath "$SESSION_DIR/.video_processed/${PADNUM}_final.mp4")"
    if [[ -f "$TAKE_FILE" ]]; then
        echo "file '$TAKE_FILE'" >> "$CONCAT_LIST"
    fi
done

echo ""
echo "Concatenating all takes..."
ffmpeg -y -f concat -safe 0 -i "$CONCAT_LIST" -c copy "$FINAL_OUTPUT" 2>/dev/null

echo ""
echo "=== Session complete: $SESSION_DIR ==="
echo "$TAKE_NUM take(s) synced."
echo ""
echo "Individual takes:"
ls -1 "$SESSION_DIR/.video_processed/"*_final.mp4 2>/dev/null
echo ""
echo "Combined: $FINAL_OUTPUT"
